language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "pypy"
env:
  - LXML=true
  - LXML=false
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install -r requirements-2.6.txt; fi
  - if [ "$LXML" == "true" ]; then pip install lxml; fi
script:
  - python -m pytest -s
notifications:
  irc:
    - "irc.freenode.org#geopython"
